version: '3.8'

x-options: &options
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"
  restart: unless-stopped
  stdin_open: true
  tty: true

volumes:
  mysql_data:
  node_modules:
  upload:
networks:
  default:

services:
  mysql:
    image: mysql:8.3.0
    ports:
      - "${MYSQL_EXTERNAL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    networks:
      default:
        aliases:
          - ${MYSQL_HOST}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 2s
      timeout: 10s
      retries: 10
    <<: *options

  node:
    build:
      context: ./../../
      dockerfile: ./docker/development/node.dockerfile
    volumes:
      - ../../:/app
      # Bind the node_modules volume
      - node_modules:/app/node_modules
    environment:
      - "MYSQL_HOST=${MYSQL_HOST}"
      - "MYSQL_PORT=${MYSQL_PORT}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "ADMIN_USER=${ADMIN_USER}"
      - "ADMIN_PASSWORD=${ADMIN_PASSWORD}"
    entrypoint: "npm start"
    ports:
      # client
      - "4200:4200"
      # api
      - "3333:3333"
        # admin
      - "3000:3000"
    networks:
      default:
        aliases:
          - node
    <<: *options
